# Generated by Django 5.2.8 on 2025-11-16 17:43

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=50, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last name')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=75, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('DESIGNER', 'Designer'), ('PRODUCT_OWNER', 'Product Owner'), ('PROJECT_OWNER', 'Project Owner'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('IOS_DEVELOPER', 'iOS Developer'), ('MOBILE_DEVELOPER', 'Mobile Developer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('DATA_SCIENTIST', 'Data Scientist'), ('DATA_ENGINEER', 'Data Engineer'), ('DATABASE_ADMIN', 'Database Admin'), ('ML_ENGINEER', 'ML Engineer'), ('PROJECT_MANAGER', 'Project Manager'), ('QA', 'QA')], default='BACKEND_DEVELOPER', max_length=25)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for time tracking', max_digits=6, null=True)),
                ('current_project', models.ForeignKey(blank=True, help_text='Primary project user is currently working on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='projects.project')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('projects', models.ManyToManyField(related_name='users', to='projects.project')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
